version: '3'

services:
    mariadb:
        build: requirements/mariadb
        container_name: mariadb
        volumes:
            - db-volume:/var/lib/mysql
        ports:
            - 3306:3306
        env_file:
            - .env
        networks:
            - inception
        restart: always
    wordpress:
        build: requirements/wordpress
        container_name: wordpress
        volumes:
            - wp-volume:/var/www/html
            - db-volume:/var/lib/mysql
        env_file:
            - .env
        depends_on:
            - mariadb
        networks:
            - inception
        restart: always
    nginx:
        build: requirements/nginx
        container_name: nginx
        depends_on:
            - wordpress
        volumes:
            - wp-volume:/var/www/html
        ports:
            - 443:443
        restart: always
        networks:
            - inception

networks:
    inception:
        driver: bridge
volumes:
  wp-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/anggonza/data/wordpress

  db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/anggonza/data/mariadb
