version: '3.3'

services:
    mariadb:
        build: requirements/mariadb
        container_name: mariadb
        volumes:
            - /home/anggonza/data/mysql:/var/lib/mysql
        env_file:
            - .env
        ports:
            - 3306:3306
        networks:
            - inception
        restart: always

networks:
    inception:
        driver: bridge
