; Start a new pool named "www"
[www]

; Listen for connections from Nginx on the socket
listen = wordpress:9000

; Set user and group ownership
listen.owner = www-data
listen.group = www-data

; Set the user and group that PHP-FPM processes will run as
user = www-data
group = www-data

; Set the number of child processes to create
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; Set the PHP-FPM environment variables
env[HOSTNAME] = $HOSTNAME
env[PATH] = /usr/local/bin:/usr/bin:/bin
env[TMP] = /tmp
env[TMPDIR] = /tmp
env[TEMP] = /tmp

; Set the PHP-FPM error log file
php_admin_value[error_log] = /var/log/php-fpm/www-error.log
